build:
  image: olymk2/scaffold
  pull: true
  commands:
#    - sleep 15
    - nose2

compose:
    mariadb:
      container_name: database
      image: olymk2/mariadb
      environment:
          # - MYSQL_BULK=test_runner|test_runner|test_runner|test_runner
          - MYSQL_USER=test_runner
          - MYSQL_PASSWORD=test_runner
          - MYSQL_DATABASE=test_runner
          - MYSQL_ROOT_PASSWORD=test_runner
