workspace:
  base: /drone
  path: src

pipeline:
  tests:
    image: python:3.5
    environment:
      - PYTHONUSERBASE=/drone/src/cache/packages
    commands:
      - pip install --cache-dir /drone/src/cache/pip -r /drone/src/requirements.txt
      - pytest

